name: event
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.2.1
  animate_do: ^4.2.0
  animated_toggle_switch: ^0.8.5
  provider: ^6.1.5
  introduction_screen: ^3.1.17
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  shared_preferences: ^2.5.3
  icons_plus: ^5.0.0
  cloud_firestore: ^5.6.8
  location: ^8.0.0
  google_maps_flutter: ^2.12.2
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
